version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jobtrackerdb
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/jobtrackerdb
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobtrackerdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
